CONNECTION_URL=jdbc:mysql://localhost:3306/skatingplanDB
LOGIN_USER=login
LOGIN_PASS=login
ATLETA_USER=atleta
ATLETA_PASS=atleta
ALLENATORE_USER=allenatore
ALLENATORE_PASS=allenatore
MANAGER_USER=manager
MANAGER_PASS=manager
